version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

aurs:
  - name: ghinst-bin
    homepage: https://github.com/tebeka/ghinst
    description: Install binaries from GitHub releases to `~/.local/bin`.
    maintainers:
      - Miki Tebeka <miki@353solutions.com>
    license: MIT
    private_key: "{{ .Env.AUR_SSH_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/ghinst-bin.git
    package: |-
      install -Dm755 "./ghinst" "${pkgdir}/usr/bin/ghinst"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/ghinst-bin/LICENSE"
